name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install 
        build-essential \ 
        libx11-dev \ 
        libxinerama-dev \
        sharutils \ 
        suckless-tools \
        libxft-dev \ 
        stterm -y
    - uses: actions/checkout@v3
    - name: Whether it'll compile
      run: make
